source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

use_frameworks!

pod 'NYSegmentedControl', :git => "https://github.com/nealyoung/NYSegmentedControl.git"
pod 'SnapKit', '~> 0.10.0'
