source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

use_frameworks!

pod 'Snap', :git => "https://github.com/Masonry/Snap.git"
pod 'NYSegmentedControl', :git => "https://github.com/nealyoung/NYSegmentedControl.git"
